### ISSUE TITLE
can openyurt support http service on edge node ?

### ISSUE THREAD

**Issue by huangzhiran** [alibaba/openyurt#121]
I have a edge node with intranet, and master node in aliyun with a public ip

can I deploy a nginx pod on edge node, and access the nginx service throw the master node public ip ?

thanks

**Comment by rambohe-ch** [comment]
@huangzhiran thank you for filing issue. 
your meaning is that can we expose the intranet service by cloud public ip or not?  
1. in fact, it is not good idea to expose edge service from cloud network because of network latency and lack of stability, so openyurt has provide this feature.
2. we recommend to expose edge service through edge ingress, like nginx ingress controller or traefik. and openyurt will provide default edge ingress solution at later.
