### ISSUE TITLE
yurt-hub can't start when I reboot node

### ISSUE THREAD

**Issue by xmwilldo** [alibaba/openyurt#47]
# yurt-hub can't start when I reboot node. 

**The reason is that the yurt-hub configuration file takes the apiserver environment variables, but the kubelet does not inject the apiserver environment variables because the yurt-hub is not running properly, so both yurt-hub and kubelet are not running normally at the end.**

**Comment by rambohe-ch** [comment]
@xmwilldo i think, we can get kube-apiserver address from /etc/kubernetes/kubelet.conf file, and set it into yurthub, or user input server-addr on the command line.

**Comment by rambohe-ch** [comment]
@charleszheng44 
 i think that we can get kube-apiserver address from /etc/kubernetes/kubelet.conf file, and set it into yurthub, or user input server-addr on the command line.

**Comment by Fei-Guo** [comment]
1. When you want to test the autonomy function of edge node by rebooting the edge node. The yurthub may not initiate properly.



For a record, this is the proposed workaround before a former code fix.


 This is because the startup parameters of yurthub are configured to read the environment variables `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT_HTTPS`, which is initialized by kubelet after connecting to apiserver.  However, kubelet can't talk to the apiserver, as the yurthub has not started yet. So you may need to temporarily modify the startup parameters of yurthub `--server-addr=https://$(KUBERNETES_SERVICE_HOST):$(KUBERNETES_SERVICE_PORT_HTTPS)` to `--server-addr=https://{apiserver-service-cluster-ip}:{apiserver-service-cluster-port}` or `--server-addr=https://{master-node-ip}:{apiserver-port}` in `yurthub.yaml`. 

    **`apiserver-service-cluster-ip` and `apiserver-service-cluster-port` can be found by `kubectl get svc/kubernetes -n default`. Also, please make sure your kube-proxy is running properly**
